### ISSUE TITLE
Chipmunk 5.2 Dll for Mingw32

### ISSUE THREAD

**Issue by Trebor777** [chipmunk-rb/chipmunk-ffi#10]
HI, 
It would be great if a Dll could be created for windows users who are not familliar with compiling stuff.. and just want to use it with ruby 1.9.1 from RubyInstaller.org ( created with Mingw32 )

Thanks a lot.

**Comment by shawn42** [comment]
I've compiled the current svn build of chipmunk; not sure what if any changes are needed to chipmunk-ffi to make this work.  Please give this a try and let me know any errors you get. Thanks!

http://github.com/downloads/shawn42/chipmunk-ffi/libchipmunk.dll

**Comment by Trebor777** [comment]
:) thanks a lot for this !!
And i got errors right from the require :

C:/Ruby191/lib/ruby/gems/1.9.1/gems/ffi-0.6.3-x86-mingw32/lib/ffi/types.rb:46:in `find_type': Unable to resolve type 'size_t' (TypeError)
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/ffi-0.6.3-x86-mingw32/lib/ffi/library.rb:267:in`find_type'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/ffi-0.6.3-x86-mingw32/lib/ffi/struct.rb:191:in `find_type'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/ffi-0.6.3-x86-mingw32/lib/ffi/struct.rb:231:in`array_layout'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/ffi-0.6.3-x86-mingw32/lib/ffi/struct.rb:158:in `layout'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/nice-ffi-0.4/lib/nice-ffi/struct.rb:104:in`layout'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/chipmunk-ffi-1.1.0/lib/chipmunk-ffi/shape.rb:25:in `<class:ShapeStruct>'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/chipmunk-ffi-1.1.0/lib/chipmunk-ffi/shape.rb:24:in`module:CP'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/chipmunk-ffi-1.1.0/lib/chipmunk-ffi/shape.rb:1:in `<top (required)>'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/chipmunk-ffi-1.1.0/lib/chipmunk-ffi.rb:44:in`require'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/chipmunk-ffi-1.1.0/lib/chipmunk-ffi.rb:44:in `block in <top (required)>'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/chipmunk-ffi-1.1.0/lib/chipmunk-ffi.rb:43:in`each'
    from C:/Ruby191/lib/ruby/gems/1.9.1/gems/chipmunk-ffi-1.1.0/lib/chipmunk-ffi.rb:43:in `<top (required)>'
